services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\FeatureContext:
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@behat.mink.default_session'
            - '@router'
